FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y wget tcptraceroute ca-certificates nmap  bc && rm -rf /var/lib/apt/lists/*

# RUN wget http://www.vdberg.org/~richard/tcpping -O /usr/bin/tcpping
# RUN chmod +x /usr/bin/tcpping
WORKDIR /app

CMD ["bash"]