apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - jobs
  - services
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - digs
  - digs/status
  - digs/finalizers
  - fios
  - fios/status
  - fios/finalizers
  - pings
  - pings/status
  - pings/finalizers
  - testreports
  - testreports/status
  - testreports/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch 