---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - digs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - digs/finalizers
  verbs:
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - digs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - fios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - fios/finalizers
  verbs:
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - fios/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - iperves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - iperves/finalizers
  verbs:
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - iperves/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - ncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - ncs/finalizers
  verbs:
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - ncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - pings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - pings/finalizers
  verbs:
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - pings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - skoops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - skoops/finalizers
  verbs:
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - skoops/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - tcppings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - tcppings/finalizers
  verbs:
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - tcppings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - testreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - testreports/finalizers
  verbs:
  - update
- apiGroups:
  - testtools.xiaoming.com
  resources:
  - testreports/status
  verbs:
  - get
  - patch
  - update
