apiVersion: testtools.xiaoming.com/v1
kind: Fio
metadata:
  name: fio-error-case
  labels:
    app: storage-benchmark
    tier: testing
spec:
  # 指定一个可能不存在或无权限的目录
  filePath: "/nonexistent/directory/test-file"
  # 读写模式
  readWrite: "randread"
  # 块大小
  blockSize: "4k"
  # IO 深度
  ioDepth: 8
  # 测试文件大小
  size: "50m"
  # IO 引擎
  ioEngine: "libaio"
  # 并行 job 数量
  numJobs: 1
  # 运行时间(秒)
  runtime: 5
  # 直接 IO (绕过操作系统缓存)
  directIO: true
  # 测试后是否删除测试文件
  deleteTestFile: true
  # 测试报告关联名称
  testReportName: "error-test-report"
  # 重试次数
  retries: 2
  # 重试间隔(秒)
  retryInterval: 30 