apiVersion: testtools.xiaoming.com/v1
kind: Fio
metadata:
  name: fio-advanced
  labels:
    app: storage-benchmark
    tier: production
spec:
  # 指定测试文件路径
  filePath: "/mnt/data/bench-file"
  # 读写模式: randread, randwrite, read, write, randrw
  readWrite: "randrw"
  # 块大小
  blockSize: "16k"
  # IO 深度
  ioDepth: 32
  # 测试文件大小
  size: "1g"
  # IO 引擎
  ioEngine: "libaio"
  # 并行 job 数量
  numJobs: 1
  # 运行时间(秒)
  runtime: 60
  # 直接 IO (绕过操作系统缓存)
  directIO: true
  # 组报告 (合并所有job的结果)
  group: true
  # 添加ExtraParams字段以支持rwmixread
  extraParams:
    rwmixread: "70"

  # 指定镜像
  image: "192.168.31.34:18093/testtools-fio:v3"