apiVersion: testtools.xiaoming.com/v1
kind: Dig
metadata:
  name: dig-failure-example
  labels:
    app: dns-monitoring
    tier: testing
spec:
  # 使用不存在的域名来模拟失败情况
  domain: "non-existent-domain-12345.invalid"
  
  # 使用Google的DNS服务器
  server: "8.8.8.8"
  
  # 查询A记录
  queryType: "A"
  
  # 设置短超时以快速失败
  timeout: 2
  
  # 最多重试2次
  maxRetries: 2


  image: "192.168.31.34:18093/testtools-dig:v3"