apiVersion: testtools.xiaoming.com/v1
kind: TcpPing
metadata:
  name: tcpping-sample-advanced
  labels:
    app: network-tools
    type: connectivity-test
spec:
  host: "kubernetes.io"
  port: 443
  count: 10
  timeout: 3
  interval: 1
  image: "192.168.31.34:18093/testtools-tcpping:v5"